name: Update HuggingFace Dataset

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day
  workflow_dispatch:

jobs:
  update-dataset:
    runs-on: ubuntu-latest
    env:
      HF_USER: ${{ vars.HF_USER }}
      HF_DATASET: ${{ vars.HF_DATASET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install bs4 requests huggingface_hub

      - name: Clone dataset
        run: |
          git clone https://huggingface.co/datasets/${HF_USER}/${HF_DATASET}

      - name: Update dataset
        run: |
          cd ${HF_DATASET}
          python ../update_hf_dataset.py
        
      - name: Commit changes to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd ${HF_DATASET}
          huggingface-cli login --token ${HF_TOKEN}
          huggingface-cli upload ${HF_USER}/${HF_DATASET} --repo-type=dataset 'boletin-oficial-argentina.jsonl'
